### ISSUE TITLE
Request to grant contributor rights

### ISSUE THREAD

**Issue by RachelMuston** [gctools-outilsgc/devex#2]
Can you grant contributor rights to @maribethbaker and @rachelmuston so that we can set up a project board and assign ourselves tasks and work openly :-)

**Comment by MaryBethBaker** [comment]
Hi @sdkibb,

Write access will allow us to update the documentation to be bilingual and GC specific. @RachelMuston Has started to modify and submit directly to the content sections of the code.

Thanks!

**Comment by sdkibb** [comment]
I think it's a great idea. We'll setup the dev so your changes go live instantly to dev, Then we'll centralize the production (beta) pulls from dev through @markwooff 
 While Mark and I get this organized I'll grant you access to the main branch but know that we'll be working primarily off the new dev branch in near future.

**Comment by MaryBethBaker** [comment]
Ok Boss! @RachelMuston and I will keep an eye out. Also this reduces our tool set down to github. We'll make the project board on the new 

Any chance you can use the @canada-ca organization for the dev version? I already have a repo setup and I think you have owner privledges.

**Comment by sdkibb** [comment]
I'll have to talk to Chris and Mark on that one. I see how being in the larger, primary, repository org is useful but not sure about fragmenting it like that. Will get back to you tomorrow.

**Comment by MaryBethBaker** [comment]
@sdkibb Sounds good.

**Comment by markwooff** [comment]
@MaryBethBaker @RachelMuston I've set up the fork under the https://github.com/canada-ca organization at https://github.com/canada-ca/devex

Will carry over all the changes we've made from this repo into the new repo, along with separating it into two branches: one for **production** and one for **dev**

**Comment by ToferC** [comment]
Go to bed. :-)

**Comment by markwooff** [comment]
@ToferC last one for the week! Enjoy the weekend 👍

**Comment by sdkibb** [comment]
Wooffman never sleeps it's seems. Great job Mark! Thanks for all your hard work this week and every week. Now, it's beer o'clock.
